In [ ]:
import numpy as np
arr= np.array([4,9,16,25,36])
print(arr)
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.sqrt(arr))

[ 4  9 16 25 36]
36
4
18.0
[2. 3. 4. 5. 6.]


In [ ]:
arr2=np.arange(1,10,1)
#  the arange function of the class np take aragumnets as  1 is the initialization , 10 is the last iteration and , 1 is the step increament
print(arr2)

[1 2 3 4 5 6 7 8 9]


In [ ]:
arr=np.linspace(0,5,5)
print(arr)

[0.   1.25 2.5  3.75 5.  ]


In [7]:
arr= np.random.randint(1,100,size=(3,3))
print(arr)
#  in this we can genrate random element of the array by using the function random and randint size is used for dimention of the array

[[56 77 76]
 [99 19 69]
 [45 69 68]]


In [34]:
# 2D array
value=np.array([[1,2,3,4,5],[3,2,5,6,7]])
# value=np.array(['a','b'])
print(value)
for i in value:
  print(i)


[[1 2 3 4 5]
 [3 2 5 6 7]]
[1 2 3 4 5]
[3 2 5 6 7]


In [36]:
print("\nArray Shape:", value.shape)
print("\nArray Size:", value.size)
print("\nArray Size:", value.dtype)



Array Shape: (2, 5)

Array Size: 10

Array Size: int64


In [49]:
# creating an array with all the vlaue as 0 zero
zero1= np.zeros([3,3])
print(zero1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [52]:
# creating an array with all the vlaue as 1 one
one1= np.ones([3,3])
print(one1)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [56]:
eye_array= np.eye(4)
print(eye_array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [59]:
# it is used to create a series of numbers in a array like arthemaic progression
ap=np.arange(0,10,2)
print(ap)

[0 2 4 6 8]


In [72]:
# it is used to generate certain number of numebr in in peticualer range then we use linespace(a,b,c) where a is the starting  b is the end and
# c is the total numebr to be genrated in that range
arr= np.linspace(0,11,5)
print(arr)

[ 0.    2.75  5.5   8.25 11.  ]


In [95]:
#  how to change the dimention of the array = by usinng the array_name.reshape(dimnetion)
arr= np.array([[3,33,55,66],[44,55,66,77],[33,55,77,88]])
arr1=arr.reshape(12)
arr2=arr.reshape(2,6)
print(arr2)
print(arr1)

[[ 3 33 55 66 44 55]
 [66 77 33 55 77 88]]
[ 3 33 55 66 44 55 66 77 33 55 77 88]


In [100]:
#traversing the element of the array by using the index number
arr= np.array([[3,33,55,66],[44,55,66,77],[33,55,77,88]])
print(arr[1][2])
print(arr[2][3])

66
88


In [123]:
# slicing of array
arr= np.array([[3,33,55,66],[44,55,66,77],[33,55,77,88]])
print(arr[0:2:1])

arr2=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr2[1:3])

print(arr2[::-1]) # reverse the array

[[ 3 33 55 66]
 [44 55 66 77]]
[2 3]
[10  9  8  7  6  5  4  3  2  1]


In [127]:
# how to add certain value to each of the value in the array
arr= np.array([[3,33,55,66],[44,55,66,77],[33,55,77,88]])
arr=arr+100
print(arr)

[[103 133 155 166]
 [144 155 166 177]
 [133 155 177 188]]


In [130]:
# how to multiply  by a certian numebr to each of the element of the array
arr= np.array([[3,33,55,66],[44,55,66,77],[33,55,77,88]])
arr=arr*10
print(arr)

[[ 30 330 550 660]
 [440 550 660 770]
 [330 550 770 880]]


In [134]:
# Addition of two array when they are having the same number of dimention
arr=np.array([2,3,4,5,6])
arr2=np.array([1,2,3,4,5])
arr3=arr+arr2
print(arr3)

[ 3  5  7  9 11]


In [137]:
# Multiplication  of two array when they are having the same number of dimention
arr=np.array([2,3,4,5,6])
arr2=np.array([1,2,3,4,5])
arr4=np.array([1,2,3,4,5])
arr3=arr*arr2*arr4
print(arr3)

[  2  12  36  80 150]


In [141]:
#  some  of the  universal funciton
# sqrt function usedd to find the square root of the values
arr=np.array([4,9,16,25,36,49,81])
arr1=np.sqrt(arr)
print(arr1)

[2. 3. 4. 5. 6. 7. 9.]


In [145]:
arr=np.array([4,9,16,25,36,49,81])
arr3=np.exp(arr)
print(arr3)

[5.45981500e+01 8.10308393e+03 8.88611052e+06 7.20048993e+10
 4.31123155e+15 1.90734657e+21 1.50609731e+35]


In [150]:
# it returns the sum of rhe array
arr=np.array([4,9,16,25,36,49,81])
sum= arr.sum()
print(sum)

arr= np.array([[3,33,55,66],[44,55,66,77],[33,55,77,88]])
sum= arr.sum()
print(sum)

220
652


In [155]:
#  how to find the min and max from the given array
arr= np.array([[3,33,55,66],[44,55,66,77],[33,55,77,88]])
max= arr.max()
print(max)

min= arr.min()
print(min)


88
3


In [160]:
#  mean and standrad deviation
arr= np.array([[3,33,55,66],[44,55,66,77],[33,55,77,88]])
mean  = arr.mean()
print(mean)
std_dev= arr.std()
print(std_dev)

54.333333333333336
22.521594575478492


In [170]:
#  how to  store the boolean vlaues ehne the condition is matched
arr= np.array([[3,33,55,66],[44,55,66,77],[33,55,77,88]])
value = arr>50
print(value)
print("*"*60)
for i in value:
  print(i,end=" ")


[[False False  True  True]
 [False  True  True  True]
 [False  True  True  True]]
************************************************************
[False False  True  True] [False  True  True  True] [False  True  True  True] 

In [175]:
#  how to filtreate the value like with a certain how to extract the values from the  given array like
# find the values which are greter then 40  from a give a certain array

arr= np.array([[3,33,55,66],[44,55,66,77],[33,55,77,88]])
arr2= arr[arr>40]
print(arr2)
print(arr[arr>50])

[55 66 44 55 66 77 55 77 88]
[55 66 55 66 77 55 77 88]


In [179]:
# broadcast in array
arr= np.array([[3,33,55,66],[44,55,66,77],[33,55,77,88]])
arr3=arr+2
print(arr3)

[[ 5 35 57 68]
 [46 57 68 79]
 [35 57 79 90]]


In [187]:
#  how to genrate and store random value in the array
#  random integers
random = np.random.randint(2,10,size=(2,2))
print(random)
print("*"*40)
random1 = np.random.randint(1,50,size=(3,5))
print(random1)


[[9 3]
 [9 9]]
****************************************
[[15 30 30 42 49]
 [21 14 25 25 39]
 [ 7 41 23 19 12]]


In [191]:
#  how to generate and stor the random flaoting numbers in to an array
random = np.random.rand(2,4)
print(random)

[[0.89774203 0.98727891 0.53094088 0.63030888]
 [0.26198917 0.29152193 0.62502015 0.14693247]]


In [195]:
#  normal distribution in an array
random = np.random.randn(2,4)
print(random)

[[ 1.49411239  0.97328133 -0.83625704 -1.59594703]
 [-1.7306799   0.90408628  0.15088395 -2.35571401]]


In [201]:
arr5 = np.array([5, 6, 7])
arr1=np.array([1,2,3])
stacked_arr = np.vstack((arr1, arr5))
print("\nVertically Stacked Array:\n", stacked_arr)


Vertically Stacked Array:
 [[1 2 3]
 [5 6 7]]


In [207]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([[1,2,3,4],[5,6,7,8]])
arr3=np.hstack((arr1,arr2))
print(arr3)

[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]
