In [8]:
import numpy as np
arr= np.array([4,9,16,25,36])
print(arr)
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.sqrt(arr))

[ 4  9 16 25 36]
36
4
18.0
[2. 3. 4. 5. 6.]


In [15]:
arr2=np.arange(1,10,1)
#  the arange function of the class np take aragumnets as  1 is the initialization , 10 is the last iteration and , 1 is the step increament
print(arr2)

[1 2 3 4 5 6 7 8 9]


In [18]:
arr=np.linspace(0,5,5)
print(arr)

[0.   1.25 2.5  3.75 5.  ]


In [24]:
arr= np.random.randint(1,100,size=(3,3))
print(arr)
#  in this we can genrate random element of the array by using the function random and randint size is used for dimention of the array

[[95  8 41]
 [11 83 63]
 [63 12 55]]
