In [97]:
import numpy as np
arr= np.array([4,9,16,25,36])
print(arr)
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.sqrt(arr))

[ 4  9 16 25 36]
36
4
18.0
[2. 3. 4. 5. 6.]


In [98]:
# . it will create an  empty array of the given dimantion with any value or we can  random vlaue
arr= np.empty((2,3))
print(arr)

[[4.9e-324 9.9e-324 2.0e-323]
 [2.0e-323 2.5e-323 3.0e-323]]


In [99]:
# empty_like(arr) it will ask for an arry and it assume the dimention of the array and create the empty array of that dimention
arr= np.array([[1,2,34],[4,5,6]])
var = np.empty_like(arr)
print(var)

[[1 2 4]
 [4 5 6]]


In [100]:
arr2=np.arange(1,10,1)
#  the arange function of the class np take aragumnets as  1 is the initialization , 10 is the last iteration and , 1 is the step increament
print(arr2)

[1 2 3 4 5 6 7 8 9]


In [101]:
arr=np.linspace(0,5,5)
print(arr)

[0.   1.25 2.5  3.75 5.  ]


In [102]:
arr= np.random.randint(1,100,size=(3,3))
print(arr)
#  in this we can genrate random element of the array by using the function random and randint size is used for dimention of the array

[[41 83 81]
 [ 6 83 59]
 [47 21 84]]


In [103]:
# 2D array
value=np.array([[1,2,3,4,5],[3,2,5,6,7]])
# value=np.array(['a','b'])
print(value)
for i in value:
  print(i)


[[1 2 3 4 5]
 [3 2 5 6 7]]
[1 2 3 4 5]
[3 2 5 6 7]


In [104]:
print("\nArray Shape:", value.shape)
print("\nArray Size:", value.size)
print("\nArray Size:", value.dtype)



Array Shape: (2, 5)

Array Size: 10

Array Size: int64


In [105]:
# creating an array with all the vlaue as 0 zero
zero1= np.zeros([3,3])
print(zero1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [106]:
# creating an array with all the vlaue as 1 one
one1= np.ones([3,3])
print(one1)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [107]:
eye_array= np.eye(4)
print(eye_array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [108]:
# it is used to create a series of numbers in a array like arthemaic progression
ap=np.arange(0,10,2)
print(ap)

[0 2 4 6 8]


In [109]:
# it is used to generate certain number of numebr in in peticualer range then we use linespace(a,b,c) where a is the starting  b is the end and
# c is the total numebr to be genrated in that range
arr= np.linspace(0,11,5)
print(arr)

[ 0.    2.75  5.5   8.25 11.  ]


In [110]:
#  how to change the dimention of the array = by usinng the array_name.reshape(dimnetion)
arr= np.array([[3,33,55,66],[44,55,66,77],[33,55,77,88]])
arr1=arr.reshape(12)
arr2=arr.reshape(2,6)
print(arr2)
print(arr1)

[[ 3 33 55 66 44 55]
 [66 77 33 55 77 88]]
[ 3 33 55 66 44 55 66 77 33 55 77 88]


In [111]:
#traversing the element of the array by using the index number
arr= np.array([[3,33,55,66],[44,55,66,77],[33,55,77,88]])
print(arr[1][2])
print(arr[2][3])

66
88


In [112]:
# slicing of array
arr= np.array([[3,33,55,66],[44,55,66,77],[33,55,77,88]])
print(arr[0:2:1])

arr2=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr2[1:3])

print(arr2[::-1]) # reverse the array

[[ 3 33 55 66]
 [44 55 66 77]]
[2 3]
[10  9  8  7  6  5  4  3  2  1]


In [113]:
# how to add certain value to each of the value in the array
arr= np.array([[3,33,55,66],[44,55,66,77],[33,55,77,88]])
arr=arr+100
print(arr)

[[103 133 155 166]
 [144 155 166 177]
 [133 155 177 188]]


In [114]:
# how to multiply  by a certian numebr to each of the element of the array
arr= np.array([[3,33,55,66],[44,55,66,77],[33,55,77,88]])
arr=arr*10
print(arr)

[[ 30 330 550 660]
 [440 550 660 770]
 [330 550 770 880]]


In [115]:
# Addition of two array when they are having the same number of dimention
arr=np.array([2,3,4,5,6])
arr2=np.array([1,2,3,4,5])
arr3=arr+arr2
print(arr3)

[ 3  5  7  9 11]


In [116]:
# Multiplication  of two array when they are having the same number of dimention
arr=np.array([2,3,4,5,6])
arr2=np.array([1,2,3,4,5])
arr4=np.array([1,2,3,4,5])
arr3=arr*arr2*arr4
print(arr3)

[  2  12  36  80 150]


In [117]:
#  some  of the  universal funciton
# sqrt function usedd to find the square root of the values
arr=np.array([4,9,16,25,36,49,81])
arr1=np.sqrt(arr)
print(arr1)

[2. 3. 4. 5. 6. 7. 9.]


In [118]:
arr=np.array([4,9,16,25,36,49,81])
arr3=np.exp(arr)
print(arr3)

[5.45981500e+01 8.10308393e+03 8.88611052e+06 7.20048993e+10
 4.31123155e+15 1.90734657e+21 1.50609731e+35]


In [119]:
# it returns the sum of rhe array
arr=np.array([4,9,16,25,36,49,81])
sum= arr.sum()
print(sum)

arr= np.array([[3,33,55,66],[44,55,66,77],[33,55,77,88]])
sum= arr.sum()
print(sum)

220
652


In [120]:
#  how to find the min and max from the given array
arr= np.array([[3,33,55,66],[44,55,66,77],[33,55,77,88]])
max= arr.max()
print(max)

min= arr.min()
print(min)


88
3


In [121]:
#  mean and standrad deviation
arr= np.array([[3,33,55,66],[44,55,66,77],[33,55,77,88]])
mean  = arr.mean()
print(mean)
std_dev= arr.std()
print(std_dev)

54.333333333333336
22.521594575478492


In [122]:
#  how to  store the boolean vlaues ehne the condition is matched
arr= np.array([[3,33,55,66],[44,55,66,77],[33,55,77,88]])
value = arr>50
print(value)
print("*"*60)
for i in value:
  print(i,end=" ")


[[False False  True  True]
 [False  True  True  True]
 [False  True  True  True]]
************************************************************
[False False  True  True] [False  True  True  True] [False  True  True  True] 

In [123]:
#  how to filtreate the value like with a certain how to extract the values from the  given array like
# find the values which are greter then 40  from a give a certain array

arr= np.array([[3,33,55,66],[44,55,66,77],[33,55,77,88]])
arr2= arr[arr>40]
print(arr2)
print(arr[arr>50])

[55 66 44 55 66 77 55 77 88]
[55 66 55 66 77 55 77 88]


In [124]:
# broadcast in array
arr= np.array([[3,33,55,66],[44,55,66,77],[33,55,77,88]])
arr3=arr+2
print(arr3)

[[ 5 35 57 68]
 [46 57 68 79]
 [35 57 79 90]]


In [125]:
#  how to genrate and store random value in the array
#  random integers
random = np.random.randint(2,10,size=(2,2))
print(random)
print("*"*40)
random1 = np.random.randint(1,50,size=(3,5))
print(random1)


[[3 5]
 [7 7]]
****************************************
[[16 10 12 29 21]
 [11 23 46 21 49]
 [ 4 15 22 36 16]]


In [126]:
#  how to generate and stor the random flaoting numbers in to an array
random = np.random.rand(2,4)
print(random)

[[0.11063743 0.67074937 0.05236073 0.21240498]
 [0.41594017 0.32632501 0.63949369 0.47065159]]


In [127]:
#  normal distribution in an array
random = np.random.randn(2,4)
print(random)

[[-0.83530859 -0.85348327  0.33032379  2.13536891]
 [ 1.09464492 -0.83793596 -1.52544049 -0.66423504]]


In [128]:
arr5 = np.array([5, 6, 7])
arr1=np.array([1,2,3])
stacked_arr = np.vstack((arr1, arr5))
print("\nVertically Stacked Array:\n", stacked_arr)


Vertically Stacked Array:
 [[1 2 3]
 [5 6 7]]


In [129]:
import numpy as np
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([[1,2,3,4],[5,6,7,8]])
arr3=np.hstack((arr1,arr2))
print(arr3)

[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]


In [130]:
#  creating a 1D array from 2D or 3D array
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr2=arr1.ravel()
print(arr2)

[1 2 3 4 5 6 7 8]


In [131]:
arr1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr1)
print("*"*20)
print("The sum of Column",arr1.sum(axis=0))
print("The sum of Rows",arr1.sum(axis=1))
print("*"*20)
arr=np.array([1,2,3,5])
print(arr.nbytes)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
********************
The sum of Column [15 18 21 24]
The sum of Rows [10 26 42]
********************
32


In [132]:
arr=np.array([1,44,55,33,66,44,33,66])
print(arr.argmax())

4


In [133]:
arr=np.array([1,44,55,33,66,44,33,66])
arr1=arr.argsort()
print(arr1)

[0 3 6 1 5 2 4 7]


In [134]:
 #  sum inbuilt function of the array can be used to  find the result  it work in the both 1D and 2D aray as well as 3D array
arr= np.array([[2,3,66,4,77,5,6],[44,100,200,1,33,55,99]])
print("Minimum= ",arr.min())
print("Maximum= ",arr.max())
print("sum of the array is = ",arr.sum())

Minimum=  1
Maximum=  200
sum of the array is =  695


In [150]:
# how to print the index of the given condtion
arr= np.array([[1,2,3],
               [4,5,6],
               [7,1,0]])
print(np.where(arr>6))
arr1=arr<5
print(arr1)
print("*"*30)
arr1=np.where(arr %2==0)
print(arr1)
# value=np.transpose(arr)
# print(value,end="")

(array([2]), array([0]))
[[ True  True  True]
 [ True False False]
 [False  True  True]]
******************************
(array([0, 1, 1, 2]), array([1, 0, 2, 2]))


In [136]:
#  np.sqrt(arr) it gives the array in which all the  root under of the elemtnt are calculted and put under the array and returnd
arr1=np.array([[9,225,4,16],[25,36,121,81]])
print(np.sqrt(arr1))

[[ 3. 15.  2.  4.]
 [ 5.  6. 11.  9.]]


In [137]:
#  it will return  the total numebr  of element that are not zero in vlaue
arr= np.array([[1,2,3],
               [4,5,6],
               [0,1,0]])
print(np.count_nonzero(arr))

7


In [138]:
#  it will return all the indedx row and column wise that are none zero
arr= np.array([[1,2,3],
               [4,5,6],
               [0,1,0]])
arr1=np.nonzero(arr)
#  now arr1 will strore   2D array in which one if the row and the second one is column which are non zero
for i in arr1:
    print(i)

[0 0 0 1 1 1 2]
[0 1 2 0 1 2 1]


In [149]:
#  lets check the size of list and an array then compare which one consume less size for the same number of element
import sys
list1=[1,2,3,4,5]
arr= np.array([1,2,3,4,5])
print("Size of python  list ",sys.getsizeof(list1))
print("size of np array ",arr.nbytes)
# print(size(arr))

Size of python  list  104
size of np array  40


In [156]:
# it will create an array with 5 *5 and follow the sequence of 1 0 0 0
                                                            #  0 1 0 0
arr=np.identity(5)
print(arr)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [157]:
# it will return the count of total number of elements which are not zero in the given array
arr= np.array([1,2,3,4,5,0,3,0])
print((np.count_nonzero(arr)))

6
